language: c++
compiler:
  - gcc
  #- clang
os:
  - linux
  #- osx
before_install:
  #mmg
  - git clone https://github.com/MmgTools/mmg.git
  - cd mmg
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../
  #lis
  - git clone https://github.com/anishida/lis.git
  - cd lis/
  #with openmp and mpi
  #- ./configure --enable-omp --enable-mpi
  #without
  - ./configure
  - make
  - sudo make install
  - cd ..
  #Petsc
  - git clone -b maint https://bitbucket.org/petsc/petsc petsc
  - cd petsc
  - export PETSC_DIR=pwd
  - export PETSC_ARCH=arch-linux2-c-debug
  - ./configure
  - make PETSC_DIR=$PETSC_DIR PETSC_ARCH=$PETSC_ARCH all
  - make PETSC_DIR=$PETSC_DIR PETSC_ARCH=$PETSC_ARCH test
  #- make PETSC_DIR=/home/norgeot/dev/ext/petsc PETSC_ARCH=arch-linux2-c-debug streams
  - echo $TRAVIS_BUILD_DIR
  - cd ..
addons:
  apt:
    packages:
      - libmpich-dev
      - libmetis-dev
      - libparmetis-dev
      - libatlas-dev
      - libeigen3-dev
      - libmumps-dev
      - libhypre-dev
      - liblapacke-dev
      - libscotch-dev
script:
  - mkdir build
  - cd build
  - cmake .. -DPETSC_DIR=$PETSC_DIR -DPETSC_ARCH=$PETSC_ARCH
  - make
  - ctest
notifications:
  email: false
